title: Narasimhan V
email: narasimhan14989@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing the knowledge gained.
baseurl: "/about/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

linkedin_username: narasimhanv
github_username:  narasimhan-v

# Build settings
markdown: kramdown
# theme: jekyll-theme-tactile
theme: minima

plugins:
  - jekyll-feed
